routes/web.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/paysera/redirect', 'PayseraGatewayController@redirect')->name('paysera-redirect');
Route::get('/paysera/callback', 'PayseraGatewayController@callback')->name('paysera-callback');
Route::get('/paysera/uzsakymas-pavyko', 'PayseraGatewayController@callback')->name('pavyko');


Route::resource('category', 'CategoryController');


Route::get('/setLang/{lang}', 'LanguageController@changeLanguage')->name('changeLanguage');


Route::get('/', 'NewsController@index')->name('homepage');


/*// Sukuriame nauja route'a
// Kelias konkrecios naujienos atvaidavimui
/* localhost/naujiena.php?id=5 */

Route::get("/news", "NewsController@index")->name('news.index');

Route::get("/news/{id}", "NewsController@show")->name('news.show')->middleware('admin');
// Istrynimo route'as
	Route::post("/news/destroy/{id}", "NewsController@destroy")->name('news.destroy');

	// Post route'as atsakingas uz formos duomenu idejima i duombaze
	Route::post("/news/update/{id}", "NewsController@update")->name('news.update');

	// Post route'as atsakingas uz formos duomenu idejima i duombaze
	Route::post("/news/store", "NewsController@store")->name('news.store');

	Route::get("/news/edit/{id}", "NewsController@edit")->name('news.edit');
Route::group(['middleware' => "auth"], function() {
	

});
	
	Route::get("/news/create", "NewsController@create")->name('news.create');

Route::get('/labas', 'NewsController@create');


// Sukuriame nauja route'a
Route::get("/comments", "CommentsController@index")->name('comments.index');

Route::get("/comments/create", "CommentsController@create")->name('comments.create')->middleware('admin');

Route::get("/comments/{id}/edit", "CommentsController@edit")->name('comments.edit');

Route::post("/comments/store", "CommentsController@store")->name('comments.store');

Route::post("/comments/{id}/update", "CommentsController@update")->name('comments.update');

Route::post('/comments/{id}/delete', 'CommentsController@destroy')->name('comments.delete');




Route::get('/skaiciuokle', 'HomeController@skaiciuokle');


// Route su pavadinimu
Route::post('/suma', 'HomeController@suma')->name('suma');





// Ieskome controllerio failio /app/http/controllers folderyje
// @index nurodo kokia funkcija naudosime is controllerio
Route::get('/kontaktai', 'HomeController@index');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use Auth;
use App;
use Gate;
// Pasakome controlleriu kad naudosime news modeli
use App\NewsItem;
use App\Comment;


class NewsController extends Controller {

	

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		// Gauname is newsItem Modelio visas naujienas ir issaugome i kintamaji

		$news = NewsItem::orderBy('created_at', "DESC")->get();
	
		// Gaunu naujienu skaiciu
		$newsCount = NewsItem::count(); // grazins skaiciu

		


		// Perduodame visas naujienas ($news) i savo view faila
		/* 1 parametras view failo pavadinimas */
		/* 2 parametras masyvas duomenu ka perduosime i view faila */
		/* 3 masyvo key kintamojo pavadinimas kaip i ji kreipsimes view faile */
		/* 4. masyvo value tai yra koki kintamaji perduodame is controlerio */

		// 1. resources/views/news.blade.php
		// 2. Kintamojo pavadinimas view faile
		// 3. Kintamojo pavadinimas controleryj

		return view( "news.index", [
			"news" => $news,
			"newsCount" => $newsCount,
		] );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {

		// kreipiuosi i resources/views/news/create.blade.php
		return view( 'news.create' );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {

		// Patikriname uzklausos duomenis
		$messages = [
			'required' => 'Laukelis :attribute turi buti uzpildytas',
			'title.required' => 'Naujienos pavadinimas turi buti uzpildytas',
			'email' => 'Laukelis :attribute turi buti el pastas'
		];

		$validatedData = $request->validate([

			// 1. Formos laukelio padinimas // 2. visos taisykles
			// Jei naudojame unique po dvitaskio duomenu bazes pavadinimas
			// kurioje reiksme turi buti unikali
			'title' => 'required|unique:news',
			'description' => 'required',
			'content' => 'required|min:10',
		], $messages);

		// naujas naujienu objektas
		$news              = new NewsItem;
		$news->title       = $request->title;
		$news->description = $request->description;
		$news->content     = $request->content;
		// Patalpinam i uploadu folderi
		$request->file('image')->store('public');

		// Priskiriam failo pavadinima i duombaze
		$news->image       = $request->file('image')->hashName();
		$news->save();


		// Susikuriu sesijos pranesima
		Session::flash( 'status', 'Naujiena sekminga sukurta' );

		return redirect()->route( 'news.index' );
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		// Kreipiames i modeli NewsItem
		/* Modelio dokumentacija :
		https://laravel.com/docs/5.6/eloquent
		*/
		$newsItem = NewsItem::find( $id );
		$menuItems = ['Naujienos', 'Komentarai', 'Kontaktai','Prisijungti'];

		if($newsItem) {
			return view( 'news.show', [
				"newsItem" => $newsItem,
				'menuItems' => $menuItems
			]);
		} else {
			return redirect()->route('news.index');
		}	
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//
		$newsItem = NewsItem::find( $id );

		return view( 'news.edit', [ 'newsItem' => $newsItem ] );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {

		// Patikriname uzklausos duomenis
		$messages = [
			'required' => 'Laukelis :attribute turi buti uzpildytas'
		];



		$validatedData = $request->validate([
			'title' => 'required|unique:news',
			'description' => 'required|email',
			'content' => 'required|min:100',
		], $messages);

		$newsItem = NewsItem::find($id);
		$newsItem->title = $request->title;
		$newsItem->description = $request->description;
		$newsItem->content = $request->content;

		$newsItem->save();

		return redirect()->route('news.show', $newsItem->id);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
		$newsItem = NewsItem::find($id);
		$newsItem->delete();
		Session::flash( 'status', 'Naujiena sekminga istrinta' );
		return redirect()->route('news.index');
	}
}

resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1> Naujieno sukurimas </h1>
        {{-- Klaidu isvedimas pagal laravelio validatoriu--}}
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <!--  Failo ikelimo laukelis -->
            <input type="file" name="image" class="form-control">
            <input
                    class="form-control"
                    placeholder="Naujienos pavadinimas"
                    {{-- Jei validacija nepraejo, tai atspausdiname senus duomenis--}}
                    value="{{ old('title') }}"
                    type="text" name="title">
            <input
                    placeholder="Naujienos aprasymas"
                    class="form-control" type="text"
                    value="{{ old('description') }}"
                    name="description">
            <label>Turinys:</label>
            <textarea class="form-control" name="content"></textarea>

            <input class="btn btn-success" type="submit">
        </form>
    </div>
@endsection

resources/views/news/edit.blade.php
@extends("layouts.app")

@section("content")
    <div class="container">
        <h1>Redaguoti naujiena</h1>
        {{-- Klaidu isvedimas pagal laravelio validatoriu--}}
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('news.update', $newsItem->id) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <input
                    class="form-control"
                    value="{{ $newsItem->title }}"
                    placeholder="Naujienos pavadinimas"
                    type="text" name="title">
            <input
                    value="{{ $newsItem->description }}"
                    placeholder="Naujienos aprasymas"
                    class="form-control" type="text" name="description">
            <label>Turinys:</label>
            <textarea class="form-control" name="content">
                {{ $newsItem->content }}
            </textarea>

            <input class="btn btn-success" type="submit">
        </form>
    </div>
@endsection

resources/views/news/index.blade.php
@extends("layouts.blog")


@section('content')
<div class="col-lg-8 col-md-10 mx-auto">
    <h1>@lang('Naujienos')</h1>
    @foreach($news as $newsItem)
          <div class="post-preview">
            <a href="{{ route('news.show', $newsItem->id) }}">
              <h2 class="post-title">
                {{ $newsItem->title }}
              </h2>
              <h3 class="post-subtitle">
                {{ $newsItem->description }}
              </h3>
            </a>
            <p class="post-meta">{{ __('Autorius') }}
              <a href="#">Start Bootstrap</a>
              on {{ $newsItem->created_at->format('Y F d') }}</p>
          </div>
          <hr>
    @endforeach
@endsection

resources/views/news/show.blade.php
@extends('layouts.blog')

@section('content')
<div class="container">

	<a href="{{ route('news.index') }}"><< {{ __('Grizti i visas naujienas') }}</a>
	
	<h1>{{ $newsItem->title }}</h1>
	Kateogrijos:
	@foreach($newsItem->categories as $category)
		<a href="{{ route('category.show', $category->id )}}">
			{{ $category->name }},
		</a>
	@endforeach
	<br>
	@can('edit_news', $newsItem)
		<a
				class="btn btn-info"
				href="{{ route('news.edit', $newsItem->id) }}">Redaguoti</a>

		<form action="{{ route('news.destroy', $newsItem->id) }}" method="POST">
			{{ csrf_field() }}

			<input type="submit" class="btn btn-danger" value="Trinti">
		</form>
	@endcan

	<p>
		{!! $newsItem->content !!}
	</p>

	<hr>
	<div class="my-3 p-3 bg-white rounded shadow-sm">
		<h2 class="border-bottom border-gray pb-2 mb-0">Komentarai 
			( {{ $newsItem->comments->count() }} )
		</h2>
		<!-- Suskaiciuoju kiek yra komentaru -->
		@if(count($newsItem->comments) > 0)
			<!--  Jei komentaru yra tai spausdinu juos -->
			@foreach($newsItem->comments as $comment)
				<div class="media text-muted pt-3">
					<div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
					<div class="d-flex justify-content-between align-items-center w-100">
		              <strong class="text-gray-dark">
		              	{{ $comment->user->email }}
		              </strong>
		            </div>
		            <span class="d-block">
		            	{{ $comment->comment_text }}
		            </span>
		            Paskelbta: {{ $comment->created_at }}
					</div>
				</div>
			@endforeach
		@else
			<!-- Jei komentaru nera tai atspausdinu kazka kito -->
			<p>
				Kolkas komentarų nėra
			</p>
		@endif
	</div>
	@if(Auth::user())
	<form action="{{ route('comments.store') }}" method="POST">
		{{ csrf_field() }}
		<h3>Pridėti komentarą</h3>
		<input type="hidden" name="news_id" value="{{ $newsItem->id }}">
		<textarea class="form-control" name="comment_text">
		</textarea>

		<input type="submit" class="btn btn-success" value="Rasyti">
	</form>
	@else 
		<a href="{{ route('login') }}">Prisijunkite </a> norėdami komentuoti
	@endif
</div>
@endsection